// <auto-generated />
using System;
using Lab1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab1.Data.Migrations
{
    [DbContext(typeof(CouponStoreDbContext))]
    partial class CouponStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Lab1.Data.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Claimed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Claimed = 0,
                            Code = "LAB1",
                            CreatedAt = new DateTime(2023, 7, 29, 12, 11, 26, 202, DateTimeKind.Utc).AddTicks(1828),
                            Discount = 0.1m,
                            IsActive = true,
                            Total = 100
                        },
                        new
                        {
                            Id = 2,
                            Claimed = 0,
                            Code = "LAB2",
                            CreatedAt = new DateTime(2023, 7, 29, 12, 11, 26, 202, DateTimeKind.Utc).AddTicks(1830),
                            Discount = 0.2m,
                            IsActive = true,
                            Total = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
